### PR TITLE
Fixing encrypted streams+moving addon ownership

### PR DESCRIPTION
**Pull request by msj33**
Hi Tommy.

Have created this pull request for fixing the encrypted DR streams asap.

Futhermore have I re/moved the "ownership", hence you mentioned that are no longer active contributer any longer. Hope that is this is fully okay with you - Else let me know :-)

You have been a VERY BIG creator and contributer over many years - So I would be more than happy to "salute" your good work in the comments/readme? You definitely deserve all the credit for the current codebase.

My aim is to create a community of code contributers on the addon and also reach out to DR for getting their approval on an open sourced addon for KODI.

Should we keep using the repo going forward, please add me as contributer or let me know, if we should move active development to my fork.

If you approve this PR, i'll proceed with merging it upstream to the offical addon repo.

Thanks again and for all the hard work done over the years.

Morten

### CODE REVIEW

**Comment by twinther** [comment]
Looks good, but complicated with the decryption part :)
Please change provider-name in addon.xml as well.

**Comment by msj33** [comment]
There you go :-)

**Comment by twinther** [comment]
Thanks. I have added you as contributor, I think you can merge this yourself now

**Comment by msj33** [comment]
Thanks - Will do + Create new release and PR for official repo

**Comment by TermeHansen** [comment]
to be fair, I think the code comes from youtube-dl and that @krogsbell borrowed it from there...

**Comment by msj33** [comment]
@TermeHansen - You are right on that one :-) - He borrowed the code-fix, and got it to work within the DR addon............and then I extracted(borrowed) it :-)

Think @krogsbell have some nice features on his fork - It even works with 1.4 API - So lets see if he wants to pitch in on the official repo.

Sharing is caring 👍

**Comment by krogsbell** [comment]
Yes I got all functions from youtube-dl and put it in my version.
My version is in a public git free to anyone.

Regards

Hans




Den tir. 5. feb. 2019 kl. 21.09 skrev msj33 <notifications@github.com>:

**Comment by msj33** [comment]
@krogsbell 

Are you interested in pushing your latest code changes/updates upstream into the "official" DR repo here?

I'm especially interested in your API 1.4 support + "Soon to expire" functionality

Instead of having fragmented repos, I suggest to consolidate our efforts into 1 repo, and keep this updated via the offical kodi addon repo.

_alternatively I can just "borrow" your code base :-P - But I would rather just have you onboard :-) _

**Comment by krogsbell** [comment]
I think that you should just borrow my codebase.

If you install on Kodi or just download the zip file and extract you have
all my code.

My interest is to be able to record the contents from the drnu addon, by
transferring links to one of my IPTV addons.

I don't expect that behaviour to go into the official repo ;-)

Regards

Hans




Den ons. 6. feb. 2019 kl. 20.20 skrev msj33 <notifications@github.com>:

**Pull request merged**
