### PR TITLE
making addon work on kodi 19 Matrix

### PR DESCRIPTION
**Pull request by TermeHansen**
This PR will re-factor the addon to python 3 to work again in kodi 19 Matrix

I suggest to bumb the version number to 5.1.0 with this change

### CODE REVIEW

**Comment by TermeHansen** [comment]
@gade01 please test this out on kodi 19

**Comment by gade01** [comment]
> @gade01 please test this out on kodi 19

@TermeHansen everything works perfectly.
Thanks so much for this.

There seems to be some extra text in the area chooser.
This should probably be removed.
image

**Comment by TermeHansen** [comment]
Ahh yes, didn't see it myself, but was a hack/solution as the controls didn't work as earlier. I'll see if I can make a better solution

**Comment by gade01** [comment]
Great, thanks.
Maybe it's possible to hide the text behind the images?

**Comment by TermeHansen** [comment]
no, found a more correct solution using the Id of the ControlButton now, just pushed it :)

**Comment by steyrs** [comment]
Just tested plugin.video.drnu-feature-kodi_19_py3.zip - on Kodi Matrix v19.

Seems to work perfectly - text in area chooser - gone - and it looks nice and tidy.
Have tried all 3 areas - and it seems to play nice.
Have switched GUI language from English to Danish - and it also seems to play along ;)

Only error so far - is when trying to watch "Løvens Hule UK" - first episode (1:15) - I will get "<random-movie-name> Unfortunately an error occurred in the DR TV addon. You can help fixing - by submitting a report...."

Other content will play just fine :)

**Comment by TermeHansen** [comment]
I'll try to reproduce

**Comment by gade01** [comment]
> no, found a more correct solution using the Id of the ControlButton now, just pushed it :)

Looking and working great now, thanks.

**Comment by maisun** [comment]
Hi, can somebody tell me how to install the new version? I tried to reach in Kodi's official repository but couldn't find the plugin "DR TV". Do I need to download somewhere any install it manually? Thanks!

**Comment by TermeHansen** [comment]
Screenshot_20210307-214801_Kodi
I see both bonanza and drnu only fresh kodi 19 here on my mobile?

**Pull request closed without merging**
