### PR TITLE
Updates for Kodi 18

### PR DESCRIPTION
**Pull request by gade01**
Changes for Kodi 18:

- Language names update
- Language folders update
- Add `assets` to addon.xml
- Add `news` to addon.xml

@TermeHansen

### CODE REVIEW

**Comment by TermeHansen** [comment]
thank you @gade01 for helping out. I just re-factored the whole code to follow the new guidelines for addons so had already change language directory names. I just added also the changes in the addon.xml as you have suggested here.

It would be very helpfull if you could test the 5.0.13 release zip, before I send it to the official repo. Seems to work fine here :)

I will close this repo

**Comment by gade01** [comment]
@TermeHansen 
No problem. I'm glad to help out as I use this addon a lot.

I only use Kodi 19 for development and on all systems.
So right now I unfortunately can't test with Kodi 18. I'll see if I can test with Kodi 18 somewhere.

,I would really like to get this fully working with Python 3 though. :)

Note that the `news` tag in addon.xml is meant more as info on latest version than a full changelog.
IMO it should not contain info on previous versions.

By the way, if you need a development repo, feel free to use mine.
I can easily add the addons required.

**Comment by pank** [comment]
I've been using 5.0.13 in libreelec (still Kodi 18) and have had no issues.

**Comment by gade01** [comment]
Oh yeah, I actually have a LibreELEC as well.
I'll test it.

@TermeHansen Is it ok if I add the newest version to my development repo?
That makes it easier to install in LibreELEC.

**Comment by TermeHansen** [comment]
@gade01 I'll follow you suggestion (as I agree on news) and release later today for official repo. You can do whatever you want in your own repo :)

**Pull request closed without merging**
