### PR TITLE
Change for current settings.xml API

### PR DESCRIPTION
**Pull request by TermeHansen**
https://kodi.wiki/view/Add-on_settings_conversion#type=%22enum%22

### CODE REVIEW

**Comment by TermeHansen** [comment]
@CodingBullywug  I was asked by kodi to update the settings.xml to the current format, and by this I also went throgh an update of the message numbering...

I think everything works as before with the settings,  but could I get you to have a look and test the addon in this PR a bit also before I merge in?

**Comment by TheWizard67** [comment]
Any update on this?

**Comment by TermeHansen** [comment]
Yes, I plan to get this in one of the next days - have you tested the branch @TheWizard67 ?

**Comment by steyrs** [comment]
@TermeHansen - I have now tested version 6.2.0 - and can no longer reproduce the issue mentioned in[#83](https://github.com/xbmc-danish-addons/plugin.video.drnu/issues/83)

Its fair to say that I have only tested the specific issue.
I will keep running this version on my Windows box - and will report back here - if I find further issues.

**Comment by TheWizard67** [comment]
> Yes, I plan to get this in one of the next days - have you tested the branch @TheWizard67 ?

Just tested it on my CoreELEC box and seems to be working as intended.

**Pull request merged**
