### PR TITLE
v5.0.13 release

### PR DESCRIPTION
**Pull request by TermeHansen**

### CODE REVIEW

**Comment by TermeHansen** [comment]
@steyrs

**Comment by steyrs** [comment]
@TermeHansen - I have now attempted to you use the provided zip.
Getting this message when I try to install it:

The dependency on xbmc.python version 2.14.0 could not be satisfied.

This is on a fresh install of Kodi Matrix v19.

install-dr-plugin-as-zip-failed-to-install-add-on-xbmc python-version-2 14 0

**Comment by TermeHansen** [comment]
thks, but this release is the last (Ithink) for kodi 18 and py27 :)

**Comment by steyrs** [comment]
Alright - will give it a shot on Kodi v18 ;)

**Pull request merged**
