### PR TITLE
new way of handling subtitles

### PR DESCRIPTION
**Pull request by TermeHansen**
I found the subtitles sometimes worked a bit stochastic, and also sometimes I was missing the danish hearofhearing subtitles when subtitles with only the foreign talk was available.

So I started a small rework where all subtitles are fetched. They are as vtt format and sadly kodi (at least at that point) will not use them if they are stored as such in a local file. So I have added a regex conversion (from somewhere on stack exchange) from vtt2srt format.

The fetched subtitles available are stored in the cachepath with then naming: "undertekster.da.srt" and "udenlandsk.da.srt" (if available). For danish videos there is only heardofhearing, for danish with some foreign talk there will be both and for foreign video only udenlandsk.da.srt... Feel free to comment on naming choices.

With this naming the subtitles are available in the sound submenu as "Danish undertekster" etc.

When setting subtitles in the api the subtitles will also automatically be used in playback. I tried to use player().showSubtitles(False), but with no luck. So the current solution for users who choose no subtitles in addon options is that I make an empty srt file if no foreign subtitles are there. and then have the subtitle list reversed depending of choice.

addon no subs: [empty.srt / udenlandsk.srt, heardofhearing.srt]
addon subs: [heardofhearing.srt, empty.srt / udenlandsk.srt]

this also means that user during playback have the option to choose between all subtitles available.

What do you think?

### CODE REVIEW

**Comment by msj33** [comment]
Hi Rasmus.

Nice work with the subtitles :-)

Unfortunately, we have already fixed the encryption issue on the repo in latest release 5.0.11+5.012.

I just published it a few hours ago.

Can you split the subtitles addition from the encryption in your PR?

Then i'll be happy to test it out - Not sure I fully understand the empty file you sugeest - Are we forced to have the subs, if extract them from the API?

P.S If your encryption method/codebase is better than current 5.0.12, please let me know, and we can do a refactoring in a seperate PR.

**Comment by TermeHansen** [comment]
I've merged with latest Master, so don't worry about  the commit history originating from my implementation of youtube-dl fix. Look at file changes they are compared to master.

**Comment by msj33** [comment]
Yes - I see now.

So a "Squash merge" is probably the best option here, to only do a single commit on Master. (then the commit history does not confuse)

Agree?

**Comment by msj33** [comment]
Do you have some examples of episodes with multi subs? -Then I can also assist with testing

**Comment by msj33** [comment]
Hi Rasmus.

Tested your solution out:

This is from Tv-avisen 18.30:
image

This is from a foreign series:
image

1)
Do DR support more than just Danish substitles and are there multiple Danish subs?

If they do, I suggest that the subtitles are simply presented as:
English
Danish
Danish(Hearing impaired/HardToHear)  <-Or whatever DR calls the "special" subs.
None

2) We should not have a mix of danish and english in the subs field - In this case, its hardcoded here.
Would be preferable that subs text uses the language files(if possible) - Current supported are English/Danish

/Morten

**Comment by TermeHansen** [comment]
I'm not sure I understand your second point.

Made a small debug print with: slug and all avaiable sub types and language:


> fantastiske-forvandlinger-iii-schweiz-3-6
> Foreign	Danish
> Foreign_HardOfHearing	Danish
> 
> 
> married-at-first-sight-us-s-5-eps-1-19-2
> Foreign	Danish
> 
> 
> bonderoeven-5-8-5
> HardOfHearing	Danish
> 
So as I see it there are three possible ways DR offer sub:
1. all danish language video -> only hardofhearing
2. mix of danish and foreign -> both danish sub (for foreign speak in video) and hardofhearing with everything)
3. foreign langue -> only danish sub (as same as hardofhearing anyhow)

**Pull request closed without merging**
